const SPORT_ACTIONS = {
  SET_POSTS: 'SET_POSTS',
  UPDATE_POSTS: 'UPDATE_POSTS',
  ADD_POSTS: 'ADD_POSTS',
  SET_COMMENTS: 'SET_COMMENTS',
  DELETE_COMMENTS: 'DELETE_COMMENTS',
  UPDATE_COMMENTS: 'UPDATE_COMMENTS',
};

export default SPORT_ACTIONS;
