const ACTIONS = {
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  CLEAR_USER_DETAILS: 'CLEAR_USER_DETAILS',
};

export default ACTIONS;
